plugins: []

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  Exclude:
    - benchmark/**/*
    - integration/**/*
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - test/**/*
    - rakelib/**/*
    - "*.gemspec"
    - lib/trakable/model.rb

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 20
  Exclude:
    - test/**/*

Metrics/ParameterLists:
  Max: 6

Metrics/AbcSize:
  Exclude:
    - test/**/*
    - lib/trakable/revertable.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/trakable/revertable.rb

Metrics/PerceivedComplexity:
  Exclude:
    - lib/trakable/revertable.rb

Lint/MissingSuper:
  Exclude:
    - lib/trakable/trak.rb

Naming/MethodParameterName:
  Exclude:
    - test/**/*

Style/OptionalBooleanParameter:
  Exclude:
    - test/**/*

Layout/LineLength:
  Exclude:
    - "*.gemspec"

Style/Documentation:
  Exclude:
    - test/**/*
    - lib/trakable/version.rb
    - lib/generators/**/*
    - lib/trakable/railtie.rb

Style/ClassAndModuleChildren:
  Enabled: false

Style/OneClassPerFile:
  Exclude:
    - test/**/*

Style/WordArray:
  Exclude:
    - test/**/*

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false
